version: '3.2'
services:
  spring-boot:
    build: .
    ports:
      - '${SPRING_BOOT_PORT}:9090'
    depends_on:
      - mariadb
    networks:
      - world_net
  mariadb:
    image: 'mariadb:10.5'
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_HOST=%'
      - 'TZ="Asia/Seoul"'
      - 'MYSQL_DATABASE=gb5'
    volumes:
      - './mysql/conf.d:/etc/mysql/conf.d'
      - '~/docker/${PROJECT_NAME}/var/lib/mysql:/var/lib/mysql'
    networks:
      - world_net
  rabbitmq:
    image: 'rabbitmq:management'
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ""
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - '5672:5672'
      - '15672:15672'
    labels:
      NAME: rabbmitmq
        - '~/docker/${PROJECT_NAME}/var/log/maria:/var/log/maria'
  mongodb:
    image: 'mongo:4.2.3'
    ports:
      - '${MONGODB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - '~/docker/${PROJECT_NAME}/data/db:/data/db'
networks:
  world_net:
    driver: bridge
